In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

bnotes = pd.read_csv('banknote-authentication - banknote-authentication.csv')

x = bnotes.drop('class', axis=1)  
y = bnotes['class']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

activations = ['relu', 'logistic', 'tanh', 'identity']

for activation in activations:
    print(f"\nTraining MLPClassifier with activation function: {activation}")
    mlp = MLPClassifier(max_iter=500, activation=activation)
    mlp.fit(x_train, y_train)
    pred = mlp.predict(x_test)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, pred))
    print("\nClassification Report:")
    print(classification_report(y_test, pred))

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

for activation in activations:
    print(f"\nTraining MLPClassifier with activation function: {activation} (Train-Test Ratio: 0.3)")
    mlp = MLPClassifier(max_iter=500, activation=activation)
    mlp.fit(x_train, y_train)
    pred = mlp.predict(x_test)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, pred))
    print("\nClassification Report:")
    print(classification_report(y_test, pred))



Training MLPClassifier with activation function: relu
Confusion Matrix:
[[149   0]
 [  0 126]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       149
           1       1.00      1.00      1.00       126

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275


Training MLPClassifier with activation function: logistic
Confusion Matrix:
[[149   0]
 [  0 126]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       149
           1       1.00      1.00      1.00       126

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275


Training MLPClassifier with activation function: tanh
Confusion Matrix:
[[149   0]
 [  0 126]]

Class

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [8]:
bnotes=pd.read_csv("banknote-authentication - banknote-authentication.csv")

NameError: name 'bnotes' is not defined

In [9]:
bnotes=pd.read_csv("banknote-authentication - banknote-authentication.csv")

In [10]:
x=bnotes.drop('class',axis=1)


In [11]:
y=bnotes['class']

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [13]:
activations = ['relu', 'logistic', 'tanh', 'identity']

In [ ]:
for activation in activations:
    print(f"\nTraining MLPClassifier with activation function: {activation}")
    mlp = MLPClassifier(max_iter=500, activation=activation)
    mlp.fit(x_train, y_train)
    pred = mlp.predict(x_test)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, pred))
    print("\nClassification Report:")
    print(classification_report(y_test, pred))
